include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/firebase_options.dart
    - lib/src/firebase_options.dart
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true
