name: afc_studymate
description: "AFC StudyMate"
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: "^3.9.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^2.5.1
  go_router: ^14.1.4
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  drift: ^2.17.0
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  flutter_hooks: ^0.20.5
  intl: ^0.19.0
  collection: ^1.18.0
  timezone: ^0.9.2
  flutter_local_notifications: ^17.2.1
  firebase_core: ^2.28.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.0
  firebase_analytics: ^11.2.0
  firebase_messaging: ^15.0.2
  package_info_plus: ^8.0.0
  share_plus: ^9.0.0
  url_launcher: ^6.2.6
  flutter_tts: ^4.0.3
  uuid: ^4.5.1
  rxdart: ^0.27.7
  equatable: ^2.0.5
  logger: ^2.5.0
  envied: ^0.5.4
  flutter_markdown: ^0.6.20
  pdf: ^3.11.0
  printing: ^5.12.0
  meta: ^1.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/db/
    - assets/images/

analyzer:
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  drift_dev: ^2.17.0
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter

