name: afc_studymate
description: "AFC StudyMate"
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: "^3.9.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^2.6.1
  go_router: ^16.2.4
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  sqlite3_flutter_libs: ^0.5.40
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  flutter_hooks: ^0.21.3+1
  intl: ^0.20.2
  collection: ^1.18.0
  timezone: ^0.10.1
  flutter_local_notifications: ^19.4.2
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  firebase_analytics: ^12.0.2
  firebase_messaging: ^16.0.2
  package_info_plus: ^9.0.0
  share_plus: ^12.0.0
  url_launcher: ^6.2.6
  flutter_tts: ^4.0.3
  uuid: ^4.5.1
  rxdart: ^0.28.0
  equatable: ^2.0.5
  logger: ^2.5.0
  envied: ^1.3.0
  flutter_markdown: ^0.7.7+1
  pdf: ^3.11.0
  printing: ^5.12.0
  meta: ^1.16.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/db/
    - assets/images/

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0
  build_runner: ^2.4.11
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  drift_dev: ^2.28.3
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter
