// GENERATED CODE - DO NOT MODIFY BY HAND
// This placeholder exists because build_runner could not be executed in the
// automated environment. Run `flutter pub run build_runner build` to generate
// the full implementation.

part of 'app_database.dart';

class _$AppDatabase extends GeneratedDatabase {
  _$AppDatabase(QueryExecutor e) : super(e);

  late final TableInfo<Table, dynamic> translations =
      throw UnimplementedError(
          'Run build_runner to generate table bindings for `translations`.');
  late final TableInfo<Table, dynamic> verses = throw UnimplementedError(
      'Run build_runner to generate table bindings for `verses`.');
  late final TableInfo<Table, dynamic> bookmarks = throw UnimplementedError(
      'Run build_runner to generate table bindings for `bookmarks`.');
  late final TableInfo<Table, dynamic> highlights = throw UnimplementedError(
      'Run build_runner to generate table bindings for `highlights`.');
  late final TableInfo<Table, dynamic> notes = throw UnimplementedError(
      'Run build_runner to generate table bindings for `notes`.');
  late final TableInfo<Table, dynamic> noteRevisions = throw UnimplementedError(
      'Run build_runner to generate table bindings for `note_revisions`.');
  late final TableInfo<Table, dynamic> lessons = throw UnimplementedError(
      'Run build_runner to generate table bindings for `lessons`.');
  late final TableInfo<Table, dynamic> lessonObjectives = throw UnimplementedError(
      'Run build_runner to generate table bindings for `lesson_objectives`.');
  late final TableInfo<Table, dynamic> lessonScriptures = throw UnimplementedError(
      'Run build_runner to generate table bindings for `lesson_scriptures`.');
  late final TableInfo<Table, dynamic> lessonAttachments = throw UnimplementedError(
      'Run build_runner to generate table bindings for `lesson_attachments`.');
  late final TableInfo<Table, dynamic> lessonQuizzes = throw UnimplementedError(
      'Run build_runner to generate table bindings for `lesson_quizzes`.');
  late final TableInfo<Table, dynamic> lessonQuizOptions = throw UnimplementedError(
      'Run build_runner to generate table bindings for `lesson_quiz_options`.');
  late final TableInfo<Table, dynamic> lessonFeeds = throw UnimplementedError(
      'Run build_runner to generate table bindings for `lesson_feeds`.');
  late final TableInfo<Table, dynamic> lessonSources = throw UnimplementedError(
      'Run build_runner to generate table bindings for `lesson_sources`.');
  late final TableInfo<Table, dynamic> progress = throw UnimplementedError(
      'Run build_runner to generate table bindings for `progress`.');
  late final TableInfo<Table, dynamic> localUsers = throw UnimplementedError(
      'Run build_runner to generate table bindings for `local_users`.');
  late final TableInfo<Table, dynamic> syncQueue = throw UnimplementedError(
      'Run build_runner to generate table bindings for `sync_queue`.');
  late final TableInfo<Table, dynamic> messages = throw UnimplementedError(
      'Run build_runner to generate table bindings for `messages`.');

  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      throw UnimplementedError('Run build_runner to generate table bindings.');

  @override
  int get schemaVersion => 6;
}

/// A lightweight stand-in for the generated [LocalUser] data class.
///
/// The real implementation is generated by `drift` via build_runner. In the
/// automated environment we ship a very small subset that is just enough for
/// the rest of the application code to compile. Any runtime usage will still
/// throw through the [UnimplementedError]s above, matching the rest of this
/// placeholder file.
class LocalUser {
  const LocalUser({
    required this.id,
    this.displayName,
    this.avatarUrl,
    this.preferredCohortId,
    this.preferredCohortTitle,
    this.preferredLessonClass,
    this.isActive = false,
  });

  final String id;
  final String? displayName;
  final String? avatarUrl;
  final String? preferredCohortId;
  final String? preferredCohortTitle;
  final String? preferredLessonClass;
  final bool isActive;

  LocalUser copyWith({
    String? id,
    String? displayName,
    String? avatarUrl,
    String? preferredCohortId,
    String? preferredCohortTitle,
    String? preferredLessonClass,
    bool? isActive,
  }) {
    return LocalUser(
      id: id ?? this.id,
      displayName: displayName ?? this.displayName,
      avatarUrl: avatarUrl ?? this.avatarUrl,
      preferredCohortId: preferredCohortId ?? this.preferredCohortId,
      preferredCohortTitle: preferredCohortTitle ?? this.preferredCohortTitle,
      preferredLessonClass:
          preferredLessonClass ?? this.preferredLessonClass,
      isActive: isActive ?? this.isActive,
    );
  }
}

/// Minimal companion used in place of the generated `LocalUsersCompanion`.
class LocalUsersCompanion {
  const LocalUsersCompanion({
    this.id = const Value.absent(),
    this.displayName = const Value.absent(),
    this.avatarUrl = const Value.absent(),
    this.preferredCohortId = const Value.absent(),
    this.preferredCohortTitle = const Value.absent(),
    this.preferredLessonClass = const Value.absent(),
    this.isActive = const Value.absent(),
  });

  LocalUsersCompanion.insert({
    required String id,
    Value<String?> displayName = const Value.absent(),
    Value<String?> avatarUrl = const Value.absent(),
    Value<String?> preferredCohortId = const Value.absent(),
    Value<String?> preferredCohortTitle = const Value.absent(),
    Value<String?> preferredLessonClass = const Value.absent(),
    Value<bool> isActive = const Value.absent(),
  })  : id = Value(id),
        displayName = displayName,
        avatarUrl = avatarUrl,
        preferredCohortId = preferredCohortId,
        preferredCohortTitle = preferredCohortTitle,
        preferredLessonClass = preferredLessonClass,
        isActive = isActive;

  final Value<String> id;
  final Value<String?> displayName;
  final Value<String?> avatarUrl;
  final Value<String?> preferredCohortId;
  final Value<String?> preferredCohortTitle;
  final Value<String?> preferredLessonClass;
  final Value<bool> isActive;

  LocalUsersCompanion copyWith({
    Value<String>? id,
    Value<String?>? displayName,
    Value<String?>? avatarUrl,
    Value<String?>? preferredCohortId,
    Value<String?>? preferredCohortTitle,
    Value<String?>? preferredLessonClass,
    Value<bool>? isActive,
  }) {
    return LocalUsersCompanion(
      id: id ?? this.id,
      displayName: displayName ?? this.displayName,
      avatarUrl: avatarUrl ?? this.avatarUrl,
      preferredCohortId: preferredCohortId ?? this.preferredCohortId,
      preferredCohortTitle:
          preferredCohortTitle ?? this.preferredCohortTitle,
      preferredLessonClass:
          preferredLessonClass ?? this.preferredLessonClass,
      isActive: isActive ?? this.isActive,
    );
  }
}
