// GENERATED CODE - DO NOT MODIFY BY HAND
// This placeholder exists because build_runner could not be executed in the
// automated environment. Run `flutter pub run build_runner build` to generate
// the full implementation.

part of 'app_database.dart';

class _$AppDatabase extends GeneratedDatabase {
  _$AppDatabase(QueryExecutor e) : super(e);

  late final TableInfo<Table, dynamic> translations =
      throw UnimplementedError(
          'Run build_runner to generate table bindings for `translations`.');
  late final TableInfo<Table, dynamic> verses = throw UnimplementedError(
      'Run build_runner to generate table bindings for `verses`.');
  late final TableInfo<Table, dynamic> bookmarks = throw UnimplementedError(
      'Run build_runner to generate table bindings for `bookmarks`.');
  late final TableInfo<Table, dynamic> highlights = throw UnimplementedError(
      'Run build_runner to generate table bindings for `highlights`.');
  late final TableInfo<Table, dynamic> notes = throw UnimplementedError(
      'Run build_runner to generate table bindings for `notes`.');
  late final TableInfo<Table, dynamic> noteRevisions = throw UnimplementedError(
      'Run build_runner to generate table bindings for `note_revisions`.');
  late final TableInfo<Table, dynamic> lessons = throw UnimplementedError(
      'Run build_runner to generate table bindings for `lessons`.');
  late final TableInfo<Table, dynamic> lessonObjectives = throw UnimplementedError(
      'Run build_runner to generate table bindings for `lesson_objectives`.');
  late final TableInfo<Table, dynamic> lessonScriptures = throw UnimplementedError(
      'Run build_runner to generate table bindings for `lesson_scriptures`.');
  late final TableInfo<Table, dynamic> lessonAttachments = throw UnimplementedError(
      'Run build_runner to generate table bindings for `lesson_attachments`.');
  late final TableInfo<Table, dynamic> lessonQuizzes = throw UnimplementedError(
      'Run build_runner to generate table bindings for `lesson_quizzes`.');
  late final TableInfo<Table, dynamic> lessonQuizOptions = throw UnimplementedError(
      'Run build_runner to generate table bindings for `lesson_quiz_options`.');
  late final TableInfo<Table, dynamic> lessonFeeds = throw UnimplementedError(
      'Run build_runner to generate table bindings for `lesson_feeds`.');
  late final TableInfo<Table, dynamic> lessonSources = throw UnimplementedError(
      'Run build_runner to generate table bindings for `lesson_sources`.');
  late final TableInfo<Table, dynamic> progress = throw UnimplementedError(
      'Run build_runner to generate table bindings for `progress`.');
  late final TableInfo<Table, dynamic> localUsers = throw UnimplementedError(
      'Run build_runner to generate table bindings for `local_users`.');
  late final TableInfo<Table, dynamic> syncQueue = throw UnimplementedError(
      'Run build_runner to generate table bindings for `sync_queue`.');
  late final TableInfo<Table, dynamic> messages = throw UnimplementedError(
      'Run build_runner to generate table bindings for `messages`.');
  late final TableInfo<Table, dynamic> typingIndicators =
      throw UnimplementedError(
          'Run build_runner to generate table bindings for `typing_indicators`.');
  late final TableInfo<Table, dynamic> moderationActionsTable =
      throw UnimplementedError(
          'Run build_runner to generate table bindings for `moderation_actions_table`.');
  late final TableInfo<Table, dynamic> moderationAppealsTable =
      throw UnimplementedError(
          'Run build_runner to generate table bindings for `moderation_appeals_table`.');
  late final TableInfo<Table, dynamic> noteChangeTrackers =
      throw UnimplementedError(
          'Run build_runner to generate table bindings for `note_change_trackers`.');
  late final TableInfo<Table, dynamic> progressChangeTrackers =
      throw UnimplementedError(
          'Run build_runner to generate table bindings for `progress_change_trackers`.');
  late final TableInfo<Table, dynamic> messageChangeTrackers =
      throw UnimplementedError(
          'Run build_runner to generate table bindings for `message_change_trackers`.');

  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      throw UnimplementedError('Run build_runner to generate table bindings.');

  @override
  int get schemaVersion => 9;
}

/// A lightweight stand-in for the generated [LocalUser] data class.
///
/// The real implementation is generated by `drift` via build_runner. In the
/// automated environment we ship a very small subset that is just enough for
/// the rest of the application code to compile. Any runtime usage will still
/// throw through the [UnimplementedError]s above, matching the rest of this
/// placeholder file.
class LocalUser {
  const LocalUser({
    required this.id,
    this.displayName,
    this.avatarUrl,
    this.preferredCohortId,
    this.preferredCohortTitle,
    this.preferredLessonClass,
    this.isActive = false,
  });

  final String id;
  final String? displayName;
  final String? avatarUrl;
  final String? preferredCohortId;
  final String? preferredCohortTitle;
  final String? preferredLessonClass;
  final bool isActive;

  LocalUser copyWith({
    String? id,
    String? displayName,
    String? avatarUrl,
    String? preferredCohortId,
    String? preferredCohortTitle,
    String? preferredLessonClass,
    bool? isActive,
  }) {
    return LocalUser(
      id: id ?? this.id,
      displayName: displayName ?? this.displayName,
      avatarUrl: avatarUrl ?? this.avatarUrl,
      preferredCohortId: preferredCohortId ?? this.preferredCohortId,
      preferredCohortTitle: preferredCohortTitle ?? this.preferredCohortTitle,
      preferredLessonClass:
          preferredLessonClass ?? this.preferredLessonClass,
      isActive: isActive ?? this.isActive,
    );
  }
}

/// Minimal companion used in place of the generated `LocalUsersCompanion`.
class LocalUsersCompanion {
  const LocalUsersCompanion({
    this.id = const Value.absent(),
    this.displayName = const Value.absent(),
    this.avatarUrl = const Value.absent(),
    this.preferredCohortId = const Value.absent(),
    this.preferredCohortTitle = const Value.absent(),
    this.preferredLessonClass = const Value.absent(),
    this.isActive = const Value.absent(),
  });

  LocalUsersCompanion.insert({
    required String id,
    Value<String?> displayName = const Value.absent(),
    Value<String?> avatarUrl = const Value.absent(),
    Value<String?> preferredCohortId = const Value.absent(),
    Value<String?> preferredCohortTitle = const Value.absent(),
    Value<String?> preferredLessonClass = const Value.absent(),
    Value<bool> isActive = const Value.absent(),
  })  : id = Value(id),
        displayName = displayName,
        avatarUrl = avatarUrl,
        preferredCohortId = preferredCohortId,
        preferredCohortTitle = preferredCohortTitle,
        preferredLessonClass = preferredLessonClass,
        isActive = isActive;

  final Value<String> id;
  final Value<String?> displayName;
  final Value<String?> avatarUrl;
  final Value<String?> preferredCohortId;
  final Value<String?> preferredCohortTitle;
  final Value<String?> preferredLessonClass;
  final Value<bool> isActive;

  LocalUsersCompanion copyWith({
    Value<String>? id,
    Value<String?>? displayName,
    Value<String?>? avatarUrl,
    Value<String?>? preferredCohortId,
    Value<String?>? preferredCohortTitle,
    Value<String?>? preferredLessonClass,
    Value<bool>? isActive,
  }) {
    return LocalUsersCompanion(
      id: id ?? this.id,
      displayName: displayName ?? this.displayName,
      avatarUrl: avatarUrl ?? this.avatarUrl,
      preferredCohortId: preferredCohortId ?? this.preferredCohortId,
      preferredCohortTitle:
          preferredCohortTitle ?? this.preferredCohortTitle,
      preferredLessonClass:
          preferredLessonClass ?? this.preferredLessonClass,
      isActive: isActive ?? this.isActive,
    );
  }
}

class Message {
  const Message({
    required this.id,
    required this.classId,
    required this.userId,
    required this.body,
    required this.createdAt,
    required this.updatedAt,
    this.deleted = false,
    this.flagged = false,
    this.attachments = '[]',
    this.authorName,
  });

  final String id;
  final String classId;
  final String userId;
  final String body;
  final int createdAt;
  final int updatedAt;
  final bool deleted;
  final bool flagged;
  final String attachments;
  final String? authorName;
}

class MessagesCompanion {
  const MessagesCompanion({
    this.id = const Value.absent(),
    this.classId = const Value.absent(),
    this.userId = const Value.absent(),
    this.body = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.updatedAt = const Value.absent(),
    this.deleted = const Value.absent(),
    this.flagged = const Value.absent(),
    this.attachments = const Value.absent(),
    this.authorName = const Value.absent(),
  });

  const MessagesCompanion.insert({
    required String id,
    required String classId,
    required String userId,
    required String body,
    required int createdAt,
    required int updatedAt,
    Value<bool> deleted = const Value(false),
    Value<bool> flagged = const Value(false),
    Value<String> attachments = const Value('[]'),
    Value<String?> authorName = const Value.absent(),
  })  : id = Value(id),
        classId = Value(classId),
        userId = Value(userId),
        body = Value(body),
        createdAt = Value(createdAt),
        updatedAt = Value(updatedAt),
        deleted = deleted,
        flagged = flagged,
        attachments = attachments,
        authorName = authorName;

  final Value<String> id;
  final Value<String> classId;
  final Value<String> userId;
  final Value<String> body;
  final Value<int> createdAt;
  final Value<int> updatedAt;
  final Value<bool> deleted;
  final Value<bool> flagged;
  final Value<String> attachments;
  final Value<String?> authorName;

  MessagesCompanion copyWith({
    Value<String>? id,
    Value<String>? classId,
    Value<String>? userId,
    Value<String>? body,
    Value<int>? createdAt,
    Value<int>? updatedAt,
    Value<bool>? deleted,
    Value<bool>? flagged,
    Value<String>? attachments,
    Value<String?>? authorName,
  }) {
    return MessagesCompanion(
      id: id ?? this.id,
      classId: classId ?? this.classId,
      userId: userId ?? this.userId,
      body: body ?? this.body,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      deleted: deleted ?? this.deleted,
      flagged: flagged ?? this.flagged,
      attachments: attachments ?? this.attachments,
      authorName: authorName ?? this.authorName,
    );
  }
}

class TypingIndicatorRow {
  const TypingIndicatorRow({
    required this.classId,
    required this.userId,
    required this.isTyping,
    required this.updatedAt,
  });

  final String classId;
  final String userId;
  final bool isTyping;
  final int updatedAt;
}

class TypingIndicatorsCompanion {
  const TypingIndicatorsCompanion({
    this.classId = const Value.absent(),
    this.userId = const Value.absent(),
    this.isTyping = const Value.absent(),
    this.updatedAt = const Value.absent(),
  });

  final Value<String> classId;
  final Value<String> userId;
  final Value<bool> isTyping;
  final Value<int> updatedAt;
}

class ModerationActionRow {
  const ModerationActionRow({
    required this.id,
    required this.classId,
    required this.targetUserId,
    required this.moderatorId,
    required this.type,
    required this.status,
    this.reason,
    required this.metadata,
    required this.createdAt,
    this.expiresAt,
  });

  final String id;
  final String classId;
  final String targetUserId;
  final String moderatorId;
  final String type;
  final String status;
  final String? reason;
  final String metadata;
  final int createdAt;
  final int? expiresAt;
}

class ModerationActionsTableCompanion {
  const ModerationActionsTableCompanion({
    this.id = const Value.absent(),
    this.classId = const Value.absent(),
    this.targetUserId = const Value.absent(),
    this.moderatorId = const Value.absent(),
    this.type = const Value.absent(),
    this.status = const Value.absent(),
    this.reason = const Value.absent(),
    this.metadata = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.expiresAt = const Value.absent(),
  });

  final Value<String> id;
  final Value<String> classId;
  final Value<String> targetUserId;
  final Value<String> moderatorId;
  final Value<String> type;
  final Value<String> status;
  final Value<String?> reason;
  final Value<String> metadata;
  final Value<int> createdAt;
  final Value<int?> expiresAt;
}

class ModerationAppealRow {
  const ModerationAppealRow({
    required this.id,
    required this.actionId,
    required this.classId,
    required this.userId,
    required this.message,
    required this.status,
    this.resolutionNotes,
    required this.createdAt,
    this.resolvedAt,
  });

  final String id;
  final String actionId;
  final String classId;
  final String userId;
  final String message;
  final String status;
  final String? resolutionNotes;
  final int createdAt;
  final int? resolvedAt;
}

class ModerationAppealsTableCompanion {
  const ModerationAppealsTableCompanion({
    this.id = const Value.absent(),
    this.actionId = const Value.absent(),
    this.classId = const Value.absent(),
    this.userId = const Value.absent(),
    this.message = const Value.absent(),
    this.status = const Value.absent(),
    this.resolutionNotes = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.resolvedAt = const Value.absent(),
  });

  final Value<String> id;
  final Value<String> actionId;
  final Value<String> classId;
  final Value<String> userId;
  final Value<String> message;
  final Value<String> status;
  final Value<String?> resolutionNotes;
  final Value<int> createdAt;
  final Value<int?> resolvedAt;
}
