name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Analyse
        run: flutter analyze
      - name: Run tests
        run: flutter test --coverage
      - name: Golden tests
        run: flutter test test/golden
      - name: Build Android APK
        run: flutter build apk --debug
      - name: Build Android App Bundle
        run: flutter build appbundle --debug
      - name: Build iOS (no codesign)
        run: flutter build ios --no-codesign
